apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waypoint
  namespace: openshift-gitops
  labels:
    environment: development
    component: waypoint
spec:
  project: default
  source:
    repoURL: https://github.com/rhdh-demo-gh/waypoint-manifests.git
    targetRevision: main
    path: development
  destination:
    server: https://kubernetes.default.svc
    namespace:waypoint-development
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
