name: YAML Lint
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  yamllint:
    name: 'YAML Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Lint (Development)'
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: 'development'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Lint (Production)'
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: 'production'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}