name: YAML Lint
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  yamllint:
    name: 'YAML Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Lint (Development)'
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: 'development/**/*.yaml'
      - name: 'Lint (Production)'
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: 'production/**/*.yaml'